### ISSUE TITLE
Textauswertung

### ISSUE THREAD

**Issue by Florianwillms** [BachelorProjektAI-HSFulda/javaturtels#1]
Suchen eines passenden Dienstes, mit dem wir die Bilddateien auswerten können, als Text zurückgeben und in unserer App abspeichern können

**Comment by mwande** [comment]
Habe ich soweit unter Kampagnen mit Ocrad.js getestet bzw. gelöst. Es funktioniert aber nicht immer zu 100% ist jedoch fürs erste Kostenlos. Nachfolgend dazu ein Screenshot. Werde ich demnächst weiter ausarbeiten und das Ergebnis pushen.

![skizze](https://user-images.githubusercontent.com/33515429/34610457-743b7178-f221-11e7-8963-981bb6411f11.png)
