### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by Florianwillms** [BachelorProjektAI-HSFulda/javaturtels#2]
Grobes Layout für schnellen zugriff. z.B.  skizze

**Comment by pierreEdimo** [comment]
Was meinst du damit?

**Comment by pierreEdimo** [comment]
Write  Preview

Leave a comment
![screenshot 1](https://user-images.githubusercontent.com/21087716/32790351-7ec6480c-c95e-11e7-9beb-73bf0344f14d.png)

**Comment by Houanco** [comment]
![crm-layout-1](https://user-images.githubusercontent.com/33424743/32793606-b905cde6-c966-11e7-9564-7b515ef5e68c.png)
Beispiel von Layout
