### ISSUE TITLE
Kamerafunktion integrieren

### ISSUE THREAD

**Issue by Sneakyjens** [BachelorProjektAI-HSFulda/javaturtels#27]
Nutzung der Kamera integrieren. Hat Vorrang, weil dies eine Kernanforderung ist.

**Comment by Komlovski** [comment]
Was meinst du mit >Kamera integrieren>/// diese funktion findet man schon in >Neue Kontakte Anlegen #17<

**Comment by Sneakyjens** [comment]
achso okay. habe die beschreibung davon nicht gelesen. hätte das aus dem titel garnicht abgeleitet.
